// Atividades por aula. Iguais nas duas edições.
// mc   = múltipla escolha: o = opções, c = índice da certa, e = explicação mostrada depois de responder
// disc = discursiva: g = pontos que uma resposta completa precisa ter (gabarito, revelado depois de enviar)
// caso = estudo de caso: mesmo formato da discursiva, mais longo
window.ATIVIDADES = {
a1: {
  mc: [
    { q: "Segundo Simon Sinek, qual é o objetivo de quem joga um jogo infinito?",
      o: ["Derrotar o concorrente principal", "Bater a meta trimestral", "Continuar jogando", "Ser o nº 1 do mercado"], c: 2,
      e: "Jogo infinito não tem linha de chegada nem vencedor. O objetivo é perpetuar o jogo; as outras opções são mentalidade finita." },
    { q: "Qual destas NÃO é característica de uma Causa Justa?",
      o: ["Afirmativa e otimista", "Inclusiva", "Alcançável no curto prazo", "Resiliente"], c: 2,
      e: "A Causa Justa é idealista: grandiosa e inalcançável, como um horizonte. As 5 características são afirmativa, inclusiva, orientada a serviço, resiliente e idealista." },
    { q: "O Projeto Aristóteles, do Google, concluiu que o fator mais importante para o sucesso de uma equipe era:",
      o: ["Competência individual dos membros", "Segurança psicológica", "Estrutura hierárquica clara", "Remuneração variável"], c: 1,
      e: "Ao analisar mais de 180 equipes, o Google viu a segurança psicológica superar competência individual e estrutura. O conceito é de Amy Edmondson." },
    { q: "\"O mesmo estado final pode ser alcançado a partir de condições iniciais diferentes e por caminhos diferentes.\" Esse é o conceito de:",
      o: ["Homeostase", "Sinergia", "Equifinalidade", "Entropia"], c: 2,
      e: "Equifinalidade é característica de sistema aberto e implica que não existe uma única melhor maneira de gerir." },
    { q: "A principal diferença entre a TGS clássica e a Teoria da Complexidade é que:",
      o: ["A TGS foca equilíbrio e homeostase; a Complexidade foca mudança, instabilidade e emergência", "A TGS trata só de sistemas fechados", "A Complexidade nega que empresas sejam sistemas abertos", "A TGS é mais recente que a Complexidade"], c: 0,
      e: "A Teoria da Complexidade (Instituto Santa Fé) atualiza a TGS: sistemas adaptativos complexos, padrões emergentes, efeito borboleta e borda do caos." },
    { q: "Na convergência dos dois conceitos da aula, o Jogo Infinito fornece ___ e o Pensamento Sistêmico fornece ___.",
      o: ["o como / o porquê", "o porquê / o como", "o orçamento / a meta", "o mapa / a bússola"], c: 1,
      e: "O Jogo Infinito é a bússola (o porquê, a Causa Justa). O Pensamento Sistêmico é o mapa (o como, as interconexões)." },
    { q: "Resiliência sistêmica (ou ecológica) é:",
      o: ["Voltar rápido ao estado anterior depois do choque", "Absorver o distúrbio e se reorganizar mantendo função e identidade, podendo até evoluir", "Evitar qualquer perturbação", "Concentrar tudo num fornecedor eficiente"], c: 1,
      e: "Voltar ao estado anterior é a resiliência de engenharia. A sistêmica vem de redundância, diversidade, modularidade e aprendizagem rápida." },
    { q: "A crítica ao pilar \"Líderes Corajosos\" e a resposta da literatura são:",
      o: ["Excesso de democracia → centralizar decisões", "Mito do líder herói → liderança distribuída", "Falta de metas → gestão por OKR", "Excesso de risco → aversão a risco"], c: 1,
      e: "Na liderança distribuída, quem está perto da informação decide, e o líder formal vira arquiteto do sistema em vez de herói." }
  ],
  disc: [
    { q: "Explique a diferença entre jogo finito e jogo infinito e por que aplicar mentalidade finita aos negócios é um erro. Use a analogia do \"atoleiro vietnamita\".",
      g: ["Finito: jogadores conhecidos, regras fixas, objetivo acordado que encerra o jogo", "Infinito: jogadores conhecidos e desconhecidos, regras mutáveis, sem fim; objetivo é continuar jogando", "Negócios são jogo infinito: não existe vencer", "Mentalidade finita (nº 1, meta trimestral) sacrifica inovação, ética e confiança", "Atoleiro: os EUA mediam batalhas e corpos sem objetivo de longo prazo; empresas presas em market share e rivalidade sem propósito"] },
    { q: "Explique as três premissas da Teoria Geral dos Sistemas e descreva uma empresa como sistema aberto (entradas, processamento, saídas, feedback).",
      g: ["Sistemas existem dentro de sistemas (hierarquia: indivíduo, organização, indústria)", "Sistemas são abertos: trocam energia, matéria e informação com o ambiente", "A função depende da estrutura", "Entradas: capital, pessoas, informação, matéria-prima", "Processamento: produção, marketing, P&D", "Saídas: produtos, serviços, lucro, resíduos", "Feedback do ambiente ajusta o comportamento; homeostase dinâmica"] },
    { q: "Por que a visão sistêmica não é nem holismo nem reducionismo? Defina os dois.",
      g: ["Reducionismo: entender o fenômeno pelas partes elementares", "Holismo: entender pelo todo e pelas relações", "Assumir só uma perspectiva perde a visão sistêmica", "Pensar sistemicamente é usar as duas ao mesmo tempo, mesmo parecendo contraditório"] }
  ],
  caso: { q: "Caso Microsoft (Satya Nadella, a partir de 2014). Identifique pelo menos 3 pilares do Jogo Infinito aplicados na virada da empresa e explique cada um com o que a Microsoft fez.",
    g: ["Causa Justa redefinida: \"capacitar cada pessoa e organização do planeta a alcançar mais\" (antes: um PC em cada mesa com Windows)", "Adversários dignos/coopetição: o Linux deixou de ser \"câncer\" e foi integrado ao Azure; virou grande contribuidora de open source", "Flexibilidade estratégica: do Windows para cloud-first, mobile-first, canibalizando o legado", "Equipes confiáveis: cultura de empatia, \"saber tudo\" → \"aprender tudo\"", "Resultado: uma das maiores reviravoltas, voltou a ser das empresas mais valiosas"] }
},

a2: {
  mc: [
    { q: "O Cisne Vermelho difere do Cisne Negro porque:",
      o: ["É mais raro", "É previsível para quem observa os sinais, mas acaba ignorado", "Só acontece em crise financeira", "É o mesmo conceito com outro nome"], c: 1,
      e: "O Cisne Negro (Taleb) é imprevisível e aleatório. O Vermelho é anunciado por sinais fracos e ignorado por viés cognitivo e inércia. Exemplos: plataformas digitais e IA generativa." },
    { q: "Na curva de adoção de Rogers, a Maioria Inicial corresponde a:",
      o: ["2,5%", "13,5%", "34%", "16%"], c: 2,
      e: "A divisão é 2,5 / 13,5 / 34 / 34 / 16. Maioria inicial e maioria tardia têm 34% cada." },
    { q: "O \"abismo\" (chasm) de Geoffrey Moore fica entre:",
      o: ["Inovadores e Adotantes Iniciais", "Adotantes Iniciais e Maioria Inicial", "Maioria Inicial e Maioria Tardia", "Maioria Tardia e Retardatários"], c: 1,
      e: "É onde a maioria das inovações morre, por não conseguir passar do nicho entusiasta para o mercado de massa." },
    { q: "No Uber, mais motoristas aumentam o valor para os passageiros e vice-versa. Isso é:",
      o: ["Efeito de rede direto", "Efeito de rede indireto", "Economia de escala", "Sazonalidade"], c: 1,
      e: "No efeito indireto, um lado da plataforma valoriza o outro (Uber, Amazon Marketplace). No direto, mais usuários beneficiam todos os usuários (WhatsApp)." },
    { q: "Crescimento autossustentado é:",
      o: ["Crescer rápido com venture capital", "Crescer com recursos gerados pela própria operação", "Crescer só por aquisições", "Crescer sem reinvestir lucro"], c: 1,
      e: "As características são receita contínua, baixa dependência de crédito, eficiência, reinvestimento e fidelização." },
    { q: "Na Matriz de Ansoff, lançar um produto novo para os clientes atuais é:",
      o: ["Penetração de mercado", "Desenvolvimento de mercado", "Desenvolvimento de produto", "Diversificação"], c: 2,
      e: "Produto novo com mercado existente é desenvolvimento de produto. Diversificação é produto novo com mercado novo." },
    { q: "A Kodak, que inventou a câmera digital em 1975 e pediu concordata em 2012, é exemplo de:",
      o: ["Crescimento autossustentado", "Crescimento autolimitado por falta de inovação", "Efeito de rede", "Sazonalidade"], c: 1,
      e: "Ela não inovou diante da digitalização. Christensen chama isso de dilema da inovação." },
    { q: "A taxa de crescimento sustentável (SGR) de Higgins mede:",
      o: ["A taxa máxima de crescimento sem alterar a estrutura de capital", "O ROI do marketing", "A participação de mercado", "O giro de estoque"], c: 0,
      e: "g* = (ROE × b) ÷ (1 − ROE × b), em que b é a proporção do lucro retido." }
  ],
  disc: [
    { q: "Diferencie crescimento autossustentado de crescimento autolimitado: definição, três características de cada e um exemplo de cada.",
      g: ["Autossustentado: expansão com recursos da própria operação, pouca dependência externa", "Características: receita contínua, baixa dependência de crédito, eficiência, reinvestimento, fidelização", "Exemplo: Nubank, Apple, Amazon Prime", "Autolimitado: expansão travada por fatores internos ou externos, estagnação ou declínio", "Características: receita estagnada, saturação de capacidade, dependência de nicho, modelo obsoleto", "Exemplo: Kodak, BlackBerry, Uber (regulação)", "Autolimitado também é oportunidade de reorganizar"] },
    { q: "Explique o que são sinais fracos e Cisnes Vermelhos e por que as organizações costumam ignorá-los.",
      g: ["Sinais fracos (Ansoff, 1975): mudanças sutis e ambíguas na periferia do sistema", "Indicam forças transformadoras antes de virarem óbvias", "Cisne Vermelho: ruptura previsível, ignorada; difere do Cisne Negro (imprevisível)", "Causas: viés cognitivo, inércia organizacional, excesso de confiança no modelo atual", "Exemplos: plataformas digitais, transição energética, IA generativa", "Resposta: construir inteligência na periferia"] },
    { q: "Escolha dois dos cinco padrões fundamentais de crescimento e explique como o gestor deve agir diante de cada um.",
      g: ["Os 5: ciclos econômicos, sazonalidade, curva de adoção, efeito de rede, cadeia de suprimentos", "Ciclos: indicadores antecedentes, caixa de reserva, corte de custo fixo", "Sazonalidade: S&OP, revenue management, estoque e contratação ajustados", "Adoção: estratégia diferente por fase, cuidado com o abismo", "Rede: subsidiar até a massa crítica, freemium", "Supply chain: diversificar fornecedores, estoque de segurança"] }
  ],
  caso: { q: "Uma rede varejista tem preço competitivo, marca reconhecida e market share consolidado, mas atrasa entregas, tem processos ineficientes e custo de produção alto. O e-commerce avança, há investimento externo disponível e falta mão de obra. Use SWOT e Ansoff: a empresa está em crescimento autolimitado? Que caminho você recomenda?",
    g: ["Monta a SWOT: forças, fraquezas internas; oportunidades, ameaças externas", "As fraquezas operacionais são fatores de crescimento autolimitado: prejudicam a experiência e a fidelização", "Investimento externo pode resolver o gargalo digital, mas exige gestão para não criar dependência", "Ansoff: em autolimitado, priorizar penetração ou desenvolvimento de mercado antes de diversificar", "Conclusão coerente e justificada"] }
},

a3: {
  mc: [
    { q: "Para Osterwalder & Pigneur, um modelo de negócio descreve:",
      o: ["O plano financeiro de cinco anos", "A lógica de criação, entrega e captura de valor", "O organograma da empresa", "A estratégia de marketing"], c: 1,
      e: "Criação é o que se produz, entrega é como chega ao cliente e captura é como a empresa ganha com isso." },
    { q: "Sobre modelo de negócio e plano de negócios:",
      o: ["O plano precede o modelo", "O modelo precede e fundamenta o plano", "São a mesma coisa", "O modelo é operacional e o plano é conceitual"], c: 1,
      e: "O modelo é conceitual e estratégico (Canvas); o plano é operacional e tático (cronograma, projeções). Se o modelo muda, o plano muda junto." },
    { q: "No Business Model Canvas, o bloco \"Fontes de Receita\" pertence à área:",
      o: ["Clientes", "Oferta", "Infraestrutura", "Viabilidade"], c: 3,
      e: "Viabilidade reúne Fontes de Receita e Estrutura de Custos. Infraestrutura reúne Recursos, Atividades e Parcerias." },
    { q: "As quatro dimensões do Triângulo Mágico do Business Model Navigator são:",
      o: ["Quem? O quê? Como? Por quê?", "Produto, Preço, Praça, Promoção", "Forças, Fraquezas, Oportunidades, Ameaças", "Missão, Visão, Valores, Metas"], c: 0,
      e: "Quem é o cliente-alvo, O quê é a proposta de valor, Como é a cadeia de valor e Por quê é o mecanismo de lucro." },
    { q: "A Amazon recebe do cliente no ato do pedido e paga o fornecedor 30 a 60 dias depois. Qual padrão é esse?",
      o: ["Long Tail", "Cash Machine", "Add-on", "Freemium"], c: 1,
      e: "O Cash Machine gera capital de giro negativo: a empresa recebe antes de pagar. A Tesla faz o mesmo com o depósito do pedido." },
    { q: "O Spotify grátis com anúncios mais uma versão premium paga segue o padrão:",
      o: ["Freemium", "Leilão", "Open Source", "Peer-to-Peer"], c: 0,
      e: "O Freemium é uma variação do Add-on para o digital. A conversão típica é de 2 a 5%, e o modelo só se paga com custo marginal perto de zero." },
    { q: "Segundo Gassmann et al., cerca de quantos % dos modelos de negócio se baseiam nos 55 padrões?",
      o: ["50%", "70%", "90%", "100%"], c: 2,
      e: "Cerca de 90%. Por isso inovar no modelo costuma ser recombinar padrões, não criar do zero." },
    { q: "O Google oferece busca grátis e cobra dos anunciantes. Qual padrão é esse?",
      o: ["Multi-sided", "Assinatura", "Razor and Blade", "Franchising"], c: 0,
      e: "Na plataforma de múltiplos lados, um lado subsidia o outro e há forte efeito de rede." },
    { q: "Por que inovar no modelo de negócio tende a gerar vantagem mais duradoura que inovar no produto?",
      o: ["Porque é mais barato", "Porque é mais difícil de copiar", "Porque não precisa de clientes", "Porque dispensa plano de negócios"], c: 1,
      e: "Envolve mudanças sistêmicas em vários elementos ao mesmo tempo, o que dificulta a imitação (Johnson, Christensen & Kagermann; Teece)." }
  ],
  disc: [
    { q: "Diferencie modelo de negócio de plano de negócios em pelo menos quatro dimensões e explique a relação entre eles.",
      g: ["Natureza: conceitual/estratégico × operacional/tático", "Foco: lógica de criação de valor × implementação prática", "Ferramenta: Canvas × documento estruturado (Sebrae)", "Objetivo: validar a lógica × orientar a execução", "O modelo precede e fundamenta o plano", "Os dois ficam vivos e conectados: mudou o modelo, muda o plano"] },
    { q: "Monte o Business Model Canvas (os 9 blocos) de uma empresa conhecida, como iFood, Netflix ou Nubank.",
      g: ["Os 9 blocos preenchidos: segmentos, proposta de valor, canais, relacionamento, receitas, recursos, atividades, parcerias, custos", "Os blocos são coerentes entre si (receita vem do segmento citado etc.)", "Proposta de valor clara e específica", "Identifica a área de cada bloco (clientes, oferta, infraestrutura, viabilidade)"] },
    { q: "Explique, com base em Teece (2010), por que criar valor não basta para um modelo de negócio dar certo.",
      g: ["Um bom modelo entrega valor a custo aceitável e captura parte suficiente dele", "Criar valor sem mecanismo de captura não gera lucro", "A captura depende de proteger ativos intangíveis, controlar recursos complementares e gerir relações com clientes e parceiros", "Exemplo que ilustra a diferença entre criar e capturar"] }
  ],
  caso: { q: "Uma academia de bairro está perdendo alunos para redes low-cost. Use o Business Model Navigator (as 4 dimensões e pelo menos 2 dos 55 padrões) para propor um modelo de negócio novo.",
    g: ["Analisa o modelo atual (iniciação)", "Muda pelo menos 2 das 4 dimensões (Quem, O quê, Como, Por quê)", "Usa padrões nomeados e coerentes (assinatura, add-on, freemium, multi-sided...)", "O mecanismo de lucro fecha: de onde vem a receita, qual o custo", "Explica por que fica difícil de copiar"] }
},

a4: {
  mc: [
    { q: "Pelo Manual de Oslo (OCDE, 1997), inovação é:",
      o: ["Criação de tecnologia inédita", "Implementação de produto, processo, método de marketing ou organizacional novo ou significativamente melhorado", "Registro de patente", "Qualquer ideia criativa"], c: 1,
      e: "A definição é ampla: vai além do tecnológico e cobre 4 domínios (produto, processo, marketing, organizacional)." },
    { q: "O Airbnb combinou internet, smartphone e pagamento online sem criar tecnologia nova. Pela apostila, isso é:",
      o: ["Invenção", "Inovação arquitetônica", "Inovação radical", "Melhoria incremental"], c: 1,
      e: "A inovação arquitetônica recombina tecnologias existentes de forma nova. Também mostra que inovação não exige invenção." },
    { q: "Na Matriz de Inovação, uma ideia \"inexistente no mundo\" com resultado esperado BAIXO é classificada como:",
      o: ["Inovação radical", "Invenção", "Melhoria", "Inovação disruptiva"], c: 2,
      e: "A matriz só tem 2 categorias, e quem decide é o resultado esperado: baixo é melhoria, médio ou alto é inovação. Invenção não é categoria da matriz." },
    { q: "A inovação disruptiva, segundo Christensen:",
      o: ["Começa com desempenho superior e preço alto", "Começa mais simples e barata, atacando segmentos ignorados, e sobe para o mercado principal", "Nasce em grandes centros de P&D", "Sempre cria tecnologia nova"], c: 1,
      e: "A radical inventa o novo, por cima. A disruptiva derruba o velho, por baixo (Uber, Netflix, Nubank)." },
    { q: "Uma mudança de comportamento que se consolida em 1 a 5 anos é:",
      o: ["Macrotendência", "Tendência", "Moda", "Novidade"], c: 1,
      e: "Macrotendência dura 5–10 anos, tendência 1–5 anos, moda até 1 ano e novidade até 2 semanas." },
    { q: "A ordem correta do ciclo de obsolescência é:",
      o: ["Substitutos → perda de diferenciação → obsolescência → queda nos resultados", "Perda de diferenciação → surgimento de substitutos → queda nos resultados → obsolescência total", "Queda nos resultados → substitutos → perda de diferenciação → obsolescência", "Obsolescência → queda → substitutos → diferenciação"], c: 1,
      e: "É um processo gradual, e a empresa costuma ler os sinais como anomalia temporária." },
    { q: "No caso dos jornais, a internet passou o poder ao consumidor sem modelo de receita adequado. Qual mecanismo de Hamel é esse?",
      o: ["São copiadas", "São suplantadas", "Esgotam-se", "Evisceram"], c: 3,
      e: "Evisceram: a estratégia transfere tanto poder ao consumidor que ele capta todo o valor." },
    { q: "No modelo dos Três Horizontes (McKinsey), o Horizonte 3:",
      o: ["Defende o core com melhorias, em 0–3 anos, com a maior parte dos recursos", "Aposta em inovações radicais ou disruptivas, em 5–10 anos, com a menor parcela dos recursos", "Cuida só de cortar custos", "É o horizonte de inovação arquitetônica, em 3–5 anos"], c: 1,
      e: "H1 defende e estende o core (0–3 anos, incremental), H2 emerge e cresce (3–5, arquitetônica) e H3 cria opções (5–10, radical ou disruptiva)." },
    { q: "Por que a demanda declarada em pesquisa é insuficiente para orientar inovação?",
      o: ["Porque é indicador lagging: mostra o que as pessoas já fazem", "Porque é indicador leading", "Porque é sempre exata", "Porque não muda com o tempo"], c: 0,
      e: "É como dirigir pelo retrovisor. As tensões (fricção, restrição, assimetria) antecipam melhor." },
    { q: "O \"mercado de limões\" de Akerlof descreve que tipo de tensão?",
      o: ["Fricção", "Restrição", "Assimetria de informação", "Sazonalidade"], c: 2,
      e: "Quando um lado sabe muito mais que o outro, o bom sai do mercado. A saída são sinais custosos e verificáveis (Spence): diploma, avaliações." }
  ],
  disc: [
    { q: "Diferencie invenção, inovação e melhoria incremental: natureza, onde acontece, como se mede o sucesso, risco e um exemplo de cada.",
      g: ["Invenção: técnico-científica, laboratório/P&D, medida pela novidade técnica, risco alto, pode nunca gerar valor (transistor, Bell Labs 1947)", "Inovação: econômica, mercado, medida pelo valor gerado, risco médio-alto, não exige invenção (Airbnb)", "Melhoria: ajuste no existente, operação, medida pela eficiência, risco baixo (câmera do iPhone, kaizen)", "Inovação é sobre novo valor, não coisa nova; quem decide é o cliente"] },
    { q: "Diferencie inovação radical de inovação disruptiva, com um exemplo de cada.",
      g: ["Radical: novo conhecimento/tecnologia de ponta, cria mercado novo, desempenho superior desde o início, mais cara, grandes empresas/P&D", "Exemplo radical: Tesla, Salesforce SaaS, internet", "Disruptiva: simplifica o existente, ataca por baixo segmentos ignorados, desempenho inicial inferior, mais barata, startups", "Exemplo disruptiva: Uber, Netflix × Blockbuster, Nubank", "Dá para ser uma sem ser a outra"] },
    { q: "Explique as três tensões de mercado (fricção, restrição e assimetria) com um exemplo de cada e enuncie a regra de ouro da taxonomia.",
      g: ["Fricção: custo energético desproporcional, \"por que é tão difícil?\" (etapas redundantes)", "Restrição: barreira de acesso, \"por que não posso acessar?\" (álbum inteiro → Spotify; democratização)", "Assimetria: desconfiança por falta de informação, \"por que não confio?\" (Akerlof; sinais de Spence; Airbnb, iFood)", "Regra de ouro: \"Resolvemos [tensão X] para [usuário Y] através de [mecanismo Z]\"", "Quem não consegue dizer isso tem uma ideia, não uma inovação"] }
  ],
  caso: { q: "Caso Kodak. Explique a queda da empresa usando o ciclo de obsolescência e o dilema do inovador, e diga o que o modelo dos Três Horizontes teria recomendado.",
    g: ["Steve Sasson inventou a câmera digital na Kodak em 1975", "O filme era 90% da receita: o medo de canibalizar travou o investimento", "Passa pelas 4 etapas do ciclo: perda de diferenciação, substitutos (digital), queda nos resultados, falência em 2012", "Dilema do inovador: excesso de foco no cliente e no modelo atual", "Três Horizontes: manter o filme no H1 e financiar o digital como H2/H3 com recursos protegidos (ambidestria)"] }
},

a5: {
  mc: [
    { q: "Chandler (1962) demonstrou que:",
      o: ["A estratégia segue a estrutura", "A estrutura segue a estratégia", "Estrutura e estratégia não se relacionam", "A estrutura é definida pelo mercado"], c: 1,
      e: "As empresas bem-sucedidas definem primeiro a estratégia e depois ajustam a estrutura para suportá-la." },
    { q: "Qual destas NÃO é uma das Cinco Forças de Porter?",
      o: ["Ameaça de novos entrantes", "Poder de barganha dos fornecedores", "Ameaça de substitutos", "Poder do governo"], c: 3,
      e: "As 5 são novos entrantes, fornecedores, compradores, substitutos e rivalidade. A política governamental aparece como barreira de entrada, não como força." },
    { q: "Uma indústria em que as cinco forças são fracas tende a ser:",
      o: ["Pouco lucrativa", "Altamente lucrativa", "Sem concorrência nenhuma", "Regulada pelo governo"], c: 1,
      e: "Exemplo: remédio patenteado. Forças fortes levam a margem baixa, como na aviação." },
    { q: "Na Matriz BCG, um produto com alta participação num mercado de baixo crescimento é:",
      o: ["Estrela", "Vaca leiteira", "Interrogação", "Cão"], c: 1,
      e: "A vaca leiteira gera caixa forte com pouco investimento, e esse caixa financia estrelas e interrogações." },
    { q: "O SmartHome Hub da TechTrend tem baixa participação e o mercado dele cresce 15% ao ano. Na BCG ele é:",
      o: ["Estrela", "Vaca leiteira", "Interrogação", "Cão"], c: 2,
      e: "Crescimento alto com participação baixa é interrogação: investir seletivamente se houver potencial, senão desinvestir." },
    { q: "No Balanced Scorecard, a cadeia de causa e efeito vai de:",
      o: ["Financeira → Clientes → Processos → Aprendizado", "Aprendizado e crescimento → Processos internos → Clientes → Financeira", "Clientes → Financeira → Aprendizado → Processos", "Processos → Financeira → Clientes → Aprendizado"], c: 1,
      e: "Treinamento melhora processos, que melhoram a satisfação do cliente, que melhora o resultado financeiro." },
    { q: "\"Em que devemos ser excelentes?\" é a pergunta de qual perspectiva do BSC?",
      o: ["Financeira", "Cliente", "Processos internos", "Aprendizado e crescimento"], c: 2,
      e: "Financeira: como os acionistas nos veem. Cliente: como os clientes nos veem. Aprendizado: podemos continuar melhorando?" },
    { q: "Diferente do Oceano Vermelho, a estratégia do Oceano Azul busca:",
      o: ["Vencer o concorrente no espaço existente", "Diferenciação e baixo custo ao mesmo tempo, criando demanda nova", "Só liderança em custos", "Disputar a demanda existente"], c: 1,
      e: "A inovação de valor rompe o trade-off valor × custo e torna a concorrência irrelevante (Cirque du Soleil)." },
    { q: "Na apostila de Planejamento Estratégico I, a Ferrari ilustra a estratégia de:",
      o: ["Liderança em custos", "Diferenciação em mercado amplo", "Foco", "Stuck in the middle"], c: 2,
      e: "Foco: atende só o segmento de altíssima renda. Na apostila II ela aparece como foco em diferenciação." },
    { q: "Vantagem competitiva transitória significa que:",
      o: ["Toda vantagem nasce, cresce e declina, e a empresa precisa criar vantagens novas continuamente", "A vantagem dura para sempre se bem defendida", "Só empresas pequenas têm vantagem", "Vantagem depende só de preço"], c: 0,
      e: "Exemplo: a Nokia tinha 40% do mercado em 2007 e foi vendida à Microsoft em 2013. A saída é estratégia adaptativa: dados, agilidade e cultura." }
  ],
  disc: [
    { q: "Aplique as Cinco Forças de Porter a uma indústria à sua escolha e conclua sobre a atratividade dela.",
      g: ["Define a indústria", "Avalia as 5 forças com fatores concretos (barreiras, concentração, custo de troca, substitutos, rivalidade)", "Classifica a intensidade de cada uma", "Conclui sobre a atratividade/lucratividade com coerência", "Aponta onde há posição menos exposta"] },
    { q: "Explique a Matriz BCG (eixos, quadrantes e estratégia de cada um) e classifique os quatro produtos da TechTrend.",
      g: ["Eixos: crescimento do mercado × participação relativa", "Estrela: investir; Vaca: colher; Interrogação: investir seletivamente ou sair; Cão: desinvestir", "SmartTrend Phone (alta participação, 3%): Vaca", "SmartHome Hub (baixa, 15%): Interrogação", "NotePro Laptop (perdendo espaço, 1%): Cão", "TrendMusic App (mediana, ~0%, custo alto): Cão"] },
    { q: "Explique o Balanced Scorecard: as quatro perspectivas, a pergunta de cada uma e a lógica de causa e efeito.",
      g: ["Nasce de Kaplan & Norton (1992) para medir também os intangíveis", "Financeira: como os acionistas nos veem?", "Cliente: como os clientes nos veem?", "Processos: em que devemos ser excelentes?", "Aprendizado: podemos continuar melhorando?", "Causa e efeito: aprendizado → processos → cliente → financeiro", "Os 6 passos de implantação (bônus)"] }
  ],
  caso: { q: "Cirque du Soleil. Explique como ele criou um Oceano Azul usando os pilares da estratégia (incluindo eliminar, reduzir, elevar, criar) e compare com o Oceano Vermelho dos circos tradicionais.",
    g: ["Contexto: circo em declínio, público envelhecendo, rejeição ao uso de animais", "Eliminou animais, celebridades, histórias lineares", "Criou narrativa, música original, arte visual do teatro e da ópera", "Público novo: adultos e empresas pagando 3 a 5 vezes mais", "Oceano Vermelho: disputar a mesma demanda com mais animais e espetáculo", "Inovação de valor: diferenciação e custo ao mesmo tempo; concorrência irrelevante"] }
},

a6: {
  mc: [
    { q: "A Visão Baseada em Recursos (RBV) adota qual perspectiva?",
      o: ["De fora para dentro", "De dentro para fora", "De cima para baixo", "De baixo para cima"], c: 1,
      e: "A RBV (Wernerfelt, Barney) olha os recursos internos únicos. A MBV de Porter olha a indústria, de fora para dentro." },
    { q: "No framework VRIO, as letras significam:",
      o: ["Valioso, Raro, Inimitável, Organizado", "Visão, Recurso, Inovação, Objetivo", "Valor, Risco, Investimento, Operação", "Vantagem, Rede, Imagem, Orçamento"], c: 0,
      e: "Um recurso com as quatro características gera vantagem competitiva sustentável." },
    { q: "\"Por que existimos?\" é a pergunta respondida pela:",
      o: ["Visão", "Missão", "Valores", "Estratégia"], c: 1,
      e: "A visão responde onde queremos chegar, e os valores respondem como nos comportamos." },
    { q: "O horizonte temporal típico da visão é:",
      o: ["O presente", "O futuro, de 3 a 10 anos", "Atemporal", "O trimestre atual"], c: 1,
      e: "A missão fica no presente, a visão no futuro e os valores são atemporais." },
    { q: "A análise PESTEL avalia:",
      o: ["O ambiente interno", "O macroambiente", "A rivalidade da indústria", "O portfólio de produtos"], c: 1,
      e: "São fatores Políticos, Econômicos, Sociais, Tecnológicos, Ecológicos e Legais. As 5 Forças avaliam o microambiente, a indústria." },
    { q: "Na SWOT cruzada, usar uma força interna para aproveitar uma oportunidade externa é estratégia:",
      o: ["Ofensiva", "De confronto", "De reforço", "Defensiva"], c: 0,
      e: "F×O é ofensiva, F×A é confronto, Fr×O é reforço e Fr×A é defensiva." },
    { q: "\"Aumentar vendas\" não é um objetivo SMART porque:",
      o: ["Não é relevante", "Falta especificidade, métrica e prazo", "É ambicioso demais", "Não envolve marketing"], c: 1,
      e: "Versão SMART: \"aumentar o market share no Nordeste em 15% até o fim de 2026, via ...\"." },
    { q: "Porter chama de \"stuck in the middle\" a empresa que:",
      o: ["Atende só um nicho", "Tenta custo e diferenciação ao mesmo tempo e não se destaca em nenhum", "Lidera em custos", "Atua em mercado intermediário"], c: 1,
      e: "O resultado é rentabilidade inferior. Há debate (Toyota), mas o conselho é ter uma estratégia primária clara." },
    { q: "No 5W2H, \"How much\" responde:",
      o: ["Quanto tempo vai levar", "Quanto vai custar", "Quantas pessoas participam", "Quantas etapas existem"], c: 1,
      e: "O orçamento estimado. Os 7 são What, Why, Where, When, Who, How e How much." },
    { q: "Segundo Ansoff & McDonnell (1993), o diagnóstico estratégico responde a duas perguntas:",
      o: ["Quanto lucrar e quanto investir", "Como identificar os desafios ambientais futuros e qual reação estratégica garante o sucesso", "Quem contratar e quem demitir", "Qual preço cobrar e de quem"], c: 1,
      e: "O diagnóstico é a análise do ambiente: PESTEL, 5 Forças e SWOT." }
  ],
  disc: [
    { q: "Compare a Market-Based View e a Resource-Based View e explique por que são complementares.",
      g: ["MBV (Porter): ambiente externo, posicionamento na indústria, de fora para dentro, 5 Forças e genéricas", "RBV (Wernerfelt, Barney): ambiente interno, recursos únicos, de dentro para fora, VRIO e core competencies", "Pressupostos: a estrutura da indústria define a rentabilidade × o recurso único define a vantagem", "Complementares: uma análise completa olha a atratividade da indústria e as capacidades internas"] },
    { q: "Diferencie missão, visão e valores (pergunta, horizonte e função) e escreva os três para uma empresa fictícia.",
      g: ["Missão: por que existimos, presente, orienta o dia a dia", "Visão: onde queremos chegar, futuro (3–10 anos), define prioridades; ambiciosa porém alcançável", "Valores: como nos comportamos, atemporais, filtram comportamentos; inegociáveis", "O exemplo fictício respeita as diferenças (missão não vira meta, visão tem horizonte)"] },
    { q: "Transforme \"melhorar o atendimento\" num objetivo SMART e monte o 5W2H de uma ação para alcançá-lo.",
      g: ["Objetivo específico, mensurável, alcançável, relevante e com prazo", "Os 7 itens do 5W2H preenchidos com coerência", "O Why conecta a ação ao objetivo", "O Who tem responsável claro e o How much tem valor"] }
  ],
  caso: { q: "Walmart × Apple. Identifique a estratégia genérica de cada uma, dois riscos de cada estratégia e uma estratégia da SWOT cruzada para cada empresa.",
    g: ["Walmart: liderança em custos (eficiência, escala, negociação, logística)", "Riscos de custo: tecnologia torna a vantagem obsoleta; qualidade cai", "Apple: diferenciação (design, ecossistema, marca, P&D, preço premium)", "Riscos de diferenciação: imitação; custo alto", "SWOT cruzada coerente para cada uma (ex.: Walmart F×O com e-commerce; Apple F×O com serviços)"] }
}
};
